version: '3.6'
services:

  node:
    build: docker/nodejs
    restart: unless-stopped
    stdin_open: true
    entrypoint: /bin/sh -c "cd /www && yarn && yarn start"
    depends_on:
      - app
    ports:
      - "3000:3000"
    volumes:
    - "./react/:/www"

  app:
    build: docker/php-fpm
    restart: unless-stopped
    depends_on:
     - db
    volumes:
     - "./:/www"
     - "./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    environment:
      - "DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}"
      - "DOCKER_XDEBUG=${DOCKER_XDEBUG}"
      - "DOCKER_SUPERVISOR=${DOCKER_SUPERVISOR}"
      - "DOCKER_CRON=${DOCKER_CRON}"

  nginx:
    image: nginx:1.21-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/www"
      - "./docker/nginx/conf.d/development.conf:/etc/nginx/conf.d/default.conf"

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - "database:/var/lib/mysql"
      - "./laravel/database/snapshots:/dumps"
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=${DOCKER_PASSWORD}"
      - "MYSQL_DATABASE=${DOCKER_DATABASE}"
      - "MYSQL_USER=${DOCKER_USERNAME}"
      - "MYSQL_PASSWORD=${DOCKER_PASSWORD}"
    command: [
      # "--general_log=1",
      # "--general_log_file=/var/lib/mysql/general_log.log",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci",
      "--default-storage-engine=innodb",
      "--innodb-file-per-table",
      "--explicit_defaults_for_timestamp=1",
      "--default-time-zone=+00:00"
    ]

volumes:
  database:
