import PropTypes from 'prop-types';
import { useSelector } from 'react-redux';
import { ThemeProvider } from 'styled-components';

import { appTheme } from 'utils/const';
import { themeApp } from 'store/themeApp';

export const colors = {
  white: '#ffffff',
  black: '#000000',
  ube: '#8688D0',
  lightCobaltBlue: '#949BF1',
  violetsAreBlue: '#8985FB',
  slateBlue: '#6764D3',
  iris: '#5856D6',
  cornflowerBlue: '#4D84EE',
  culturedLight: '#F3F6FA',
  columbiaBlue: '#CAD5E8',
  lavender: '#E2E7FB',
  oldLace: '#FBF6E2',
  pearl: '#E8DDCA',
  silver: '#C9C9C9',
  concretesolid: '#F2F2F2',
  cultured: '#FAF7F3',
  spanishGray: '#939393',
  silverChalice: '#AEAEAE',
  mintGreen: '#9EffA8',
  pastelGreen: '#72DB7D',
  kiwi: '#90DC45',
  blueberry: '#EEB74D',
  cadetBlue: '#AFB0CB',
  romanSilver: '#80819C',
  blackCoral: '#5B5B74',
  darkBlueGray: '#606188',
  charcoal: '#3D3E56',
  yankeesBlue: '#262739',
  darkGunmetal: '#20212D',
  darkCharcoal: '#303030',
  outerSpace: '#484848',
  outerSpaceLight: '#474747',
  westchesterGrey: '#787878',
  capeHope: '#D7D7D7',
  alto: '#DFDFDF',
  catskillWhite: '#F3F6fA',
};

export const theme = {
  [appTheme.light]: {
    logo: colors.violetsAreBlue,
    background: colors.culturedLight,
    error: `red`,
    font: {
      primary: colors.outerSpace,
      title: colors.darkCharcoal,
    },
    sidebar: colors.lightCobaltBlue,
    navLink: {
      primary: colors.white,
      hover: colors.white,
      active: colors.outerSpace,
      bg: colors.violetsAreBlue,
      bgHover: colors.slateBlue,
      bgActive: colors.white,
      svg: colors.white,
      svgActive: colors.white,
    },
    linkBtn: {
      primary: colors.white,
      hover: colors.white,
      active: colors.outerSpace,
      bg: colors.violetsAreBlue,
      bgHover: colors.slateBlue,
      bgActive: colors.white,
      border: colors.violetsAreBlue,
      borderHover: colors.slateBlue,
    },
    field: {
      labelColor: colors.westchesterGrey,
      labelBgColor: colors.white,
      textColor: colors.outerSpace,
      bgColor: 'transparent',
      borderColor: colors.columbiaBlue,
      bgFocus: colors.white,
      colorTextFocus: colors.black,
      bgSelect: colors.white,
      bgSearch: colors.culturedLight,
      placeholder: colors.silverChalice,
      placeholderFocus: colors.silverChalice,
    },
    switchBtn: {
      bgActive: colors.violetsAreBlue,
      bgСircleActive: colors.white,
      bgInactive: colors.spanishGray,
      bgСircleInactive: colors.culturedLight,
    },

    button: {
      primary: {
        color: colors.white,
        border: colors.violetsAreBlue,
        bg: colors.violetsAreBlue,
        bgHover: colors.iris,
        borderHover: colors.iris,
      },
      alternative: {
        color: colors.lavender,
        borderOutlined: colors.slateBlue,
        border: colors.slateBlue,
        borderHover: colors.darkCharcoal,
        bg: colors.slateBlue,
        bgHover: colors.darkCharcoal,
      },
    },
    table: {
      headerColor: colors.lavender,
      font: colors.outerSpace,
      fontHead: colors.westchesterGrey,
      bgHead: colors.white,
      bgHeadHover: colors.violetsAreBlue,
      optionBg: colors.columbiaBlue,
      optionHover: colors.violetsAreBlue,
      active: {
        font: colors.white,
        bg: colors.kiwi,
      },
      disabled: {
        font: colors.spanishGray,
        bg: colors.lavender,
      },
      popupOption: {
        bgMain: colors.white,
        bg: colors.white,
        bgHover: colors.lavender,
        border: colors.lightCobaltBlue,
        text: colors.ube,
      },
      email: colors.cornflowerBlue,
      priceId: colors.cornflowerBlue,
      country: colors.outerSpace,
      location: colors.outerSpace,
    },
    popup: {
      bg: colors.culturedLight,
      border: colors.lightCobaltBlue,
      title: colors.outerSpace,
      text: colors.westchesterGrey,
      confirmBg: colors.lavender,
      confirmColor: colors.westchesterGrey,
      confirmBgHover: colors.silver,
      cancelBg: colors.iris,
    },
    btnBack: {
      color: colors.lightCobaltBlue,
      colorHover: colors.slateBlue,
    },
    dropdown: {
      optionBg: colors.concretesolid,
      optionBgHover: colors.lavender,
      optionColor: colors.westchesterGrey,
      optionColorHover: colors.westchesterGrey,
    },
    titleH2: colors.outerSpace,
    pagination: {
      color: colors.spanishGray,
      bgActive: colors.lightCobaltBlue,
      colorActive: colors.white,
    },
  },
  [appTheme.dark]: {
    logo: colors.white,
    background: colors.yankeesBlue,
    error: `red`,
    font: {
      primary: colors.outerSpace,
      title: colors.darkCharcoal,
    },
    field: {
      labelColor: colors.cadetBlue,
      labelBgColor: colors.white,
      textColor: colors.concretesolid,
      bgColor: 'transparent',
      borderColor: colors.charcoal,
      bgFocus: colors.oldLace,
      colorTextFocus: colors.concretesolid,
      bgSelect: colors.charcoal,
      bgSearch: colors.charcoal,
      borderSearch: colors.charcoal,
      placeholder: colors.cadetBlue,
      placeholderFocus: colors.cadetBlue,
    },
    switchBtn: {
      bgActive: colors.iris,
      bgСircleActive: colors.white,
      bgInactive: colors.darkGunmetal,
      bgСircleInactive: colors.darkBlueGray,
    },
    sidebar: colors.charcoal,
    navLink: {
      primary: colors.cadetBlue,
      hover: colors.cadetBlue,
      active: colors.white,
      bg: colors.charcoal,
      bgHover: colors.yankeesBlue,
      bgActive: colors.darkBlueGray,
      svg: colors.cadetBlue,
      svgActive: colors.white,
    },
    linkBtn: {
      primary: colors.white,
      hover: colors.white,
      active: colors.outerSpace,
      bg: colors.violetsAreBlue,
      bgHover: colors.slateBlue,
      bgActive: colors.white,
      border: colors.violetsAreBlue,
      borderHover: colors.white,
    },
    button: {
      primary: {
        color: colors.white,
        border: colors.violetsAreBlue,
        bg: colors.violetsAreBlue,
        bgHover: colors.violetsAreBlue,
        borderHover: colors.cultured,
      },
      alternative: {
        color: colors.lavender,
        borderOutlined: colors.slateBlue,
        border: 'rgba(38, 39, 57, 0.5)',
        borderHover: colors.cultured,
        bg: 'rgba(38, 39, 57, 0.5)',
        bgHover: 'rgba(38, 39, 57, 0.5)',
      },
    },
    table: {
      headerColor: colors.darkGunmetal,
      font: colors.cadetBlue,
      bgHead: colors.charcoal,
      bgHeadHover: colors.darkBlueGray,
      optionBg: colors.charcoal,
      optionHover: colors.darkBlueGray,
      active: {
        font: colors.pastelGreen,
        bg: 'rgba(158, 255, 168, 0.24)',
      },
      disabled: {
        font: colors.cadetBlue,
        bg: 'rgba(91, 92, 116, 0.34)',
      },
      popupOption: {
        bgMain: colors.charcoal,
        bg: colors.charcoal,
        bgHover: colors.darkBlueGray,
        border: 'rgba(0 0 0/ 20%)',
        text: colors.ube,
      },
      email: colors.ube,
      priceId: colors.ube,
      country: colors.capeHope,
      location: colors.capeHope,
    },
    popup: {
      bg: colors.yankeesBlue,
      border: 'rgba(0, 0, 0, 0.4)',
      title: colors.concretesolid,
      text: colors.cadetBlue,
      confirmBg: colors.charcoal,
      confirmColor: colors.concretesolid,
      cancelBg: colors.iris,
    },
    btnBack: {
      color: colors.cadetBlue,
      colorHover: colors.ube,
    },
    dropdown: {
      optionBg: colors.charcoal,
      optionBgHover: colors.darkBlueGray,
      optionColor: colors.cadetBlue,
      optionColorHover: colors.cadetBlue,
    },
    titleH2: colors.concretesolid,
    pagination: {
      color: colors.blackCoral,
      bgActive: colors.charcoal,
      colorActive: colors.concretesolid,
    },
  },
};

Theme.propTypes = {
  children: PropTypes.node,
};

function Theme({ children }) {
  const mode = useSelector(themeApp.selectors.themeApp);
  return <ThemeProvider theme={theme[mode]}>{children}</ThemeProvider>;
}

export default Theme;
