<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ["name"=>"Aruba", "iso_code"=>"AW"],
            ["name"=>"Afghanistan", "iso_code"=>"AF"],
            ["name"=>"Angola", "iso_code"=>"AO"],
            ["name"=>"Anguilla", "iso_code"=>"AI"],
            ["name"=>"Åland Islands", "iso_code"=>"AX"],
            ["name"=>"Albania", "iso_code"=>"AL"],
            ["name"=>"Andorra", "iso_code"=>"AD"],
            ["name"=>"United Arab Emirates", "iso_code"=>"AE"],
            ["name"=>"Argentina", "iso_code"=>"AR"],
            ["name"=>"Armenia", "iso_code"=>"AM"],
            ["name"=>"American Samoa", "iso_code"=>"AS"],
            ["name"=>"French Southern and Antarctic Lands", "iso_code"=>"TF"],
            ["name"=>"Antigua and Barbuda", "iso_code"=>"AG"],
            ["name"=>"Australia", "iso_code"=>"AU"],
            ["name"=>"Austria", "iso_code"=>"AT"],
            ["name"=>"Azerbaijan", "iso_code"=>"AZ"],
            ["name"=>"Burundi", "iso_code"=>"BI"],
            ["name"=>"Belgium", "iso_code"=>"BE"],
            ["name"=>"Benin", "iso_code"=>"BJ"],
            ["name"=>"Burkina Faso", "iso_code"=>"BF"],
            ["name"=>"Bangladesh", "iso_code"=>"BD"],
            ["name"=>"Bulgaria", "iso_code"=>"BG"],
            ["name"=>"Bahrain", "iso_code"=>"BH"],
            ["name"=>"Bahamas", "iso_code"=>"BS"],
            ["name"=>"Bosnia and Herzegovina", "iso_code"=>"BA"],
            ["name"=>"Saint Barthélemy", "iso_code"=>"BL"],
            ["name"=>"Saint Helena, Ascension and Tristan da Cunha", "iso_code"=>"SH"],
            ["name"=>"Belarus", "iso_code"=>"BY"],
            ["name"=>"Belize", "iso_code"=>"BZ"],
            ["name"=>"Bermuda", "iso_code"=>"BM"],
            ["name"=>"Bolivia", "iso_code"=>"BO"],
            ["name"=>"Brazil", "iso_code"=>"BR"],
            ["name"=>"Barbados", "iso_code"=>"BB"],
            ["name"=>"Brunei", "iso_code"=>"BN"],
            ["name"=>"Bhutan", "iso_code"=>"BT"],
            ["name"=>"Botswana", "iso_code"=>"BW"],
            ["name"=>"Central African Republic", "iso_code"=>"CF"],
            ["name"=>"Canada", "iso_code"=>"CA"],
            ["name"=>"Switzerland", "iso_code"=>"CH"],
            ["name"=>"Chile", "iso_code"=>"CL"],
            ["name"=>"China", "iso_code"=>"CN"],
            ["name"=>"Ivory Coast", "iso_code"=>"CI"],
            ["name"=>"Cameroon", "iso_code"=>"CM"],
            ["name"=>"DR Congo", "iso_code"=>"CD"],
            ["name"=>"Republic of the Congo", "iso_code"=>"CG"],
            ["name"=>"Cook Islands", "iso_code"=>"CK"],
            ["name"=>"Colombia", "iso_code"=>"CO"],
            ["name"=>"Comoros", "iso_code"=>"KM"],
            ["name"=>"Cape Verde", "iso_code"=>"CV"],
            ["name"=>"Costa Rica", "iso_code"=>"CR"],
            ["name"=>"Cuba", "iso_code"=>"CU"],
            ["name"=>"Curaçao", "iso_code"=>"CW"],
            ["name"=>"Cayman Islands", "iso_code"=>"KY"],
            ["name"=>"Cyprus", "iso_code"=>"CY"],
            ["name"=>"Czechia", "iso_code"=>"CZ"],
            ["name"=>"Germany", "iso_code"=>"DE"],
            ["name"=>"Djibouti", "iso_code"=>"DJ"],
            ["name"=>"Dominica", "iso_code"=>"DM"],
            ["name"=>"Denmark", "iso_code"=>"DK"],
            ["name"=>"Dominican Republic", "iso_code"=>"DO"],
            ["name"=>"Algeria", "iso_code"=>"DZ"],
            ["name"=>"Ecuador", "iso_code"=>"EC"],
            ["name"=>"Egypt", "iso_code"=>"EG"],
            ["name"=>"Eritrea", "iso_code"=>"ER"],
            ["name"=>"Western Sahara", "iso_code"=>"EH"],
            ["name"=>"Spain", "iso_code"=>"ES"],
            ["name"=>"Estonia", "iso_code"=>"EE"],
            ["name"=>"Ethiopia", "iso_code"=>"ET"],
            ["name"=>"Finland", "iso_code"=>"FI"],
            ["name"=>"Fiji", "iso_code"=>"FJ"],
            ["name"=>"Falkland Islands", "iso_code"=>"FK"],
            ["name"=>"France", "iso_code"=>"FR"],
            ["name"=>"Faroe Islands", "iso_code"=>"FO"],
            ["name"=>"Micronesia", "iso_code"=>"FM"],
            ["name"=>"Gabon", "iso_code"=>"GA"],
            ["name"=>"United Kingdom", "iso_code"=>"GB"],
            ["name"=>"Georgia", "iso_code"=>"GE"],
            ["name"=>"Guernsey", "iso_code"=>"GG"],
            ["name"=>"Ghana", "iso_code"=>"GH"],
            ["name"=>"Gibraltar", "iso_code"=>"GI"],
            ["name"=>"Guinea", "iso_code"=>"GN"],
            ["name"=>"Gambia", "iso_code"=>"GM"],
            ["name"=>"Guinea-Bissau", "iso_code"=>"GW"],
            ["name"=>"Equatorial Guinea", "iso_code"=>"GQ"],
            ["name"=>"Greece", "iso_code"=>"GR"],
            ["name"=>"Grenada", "iso_code"=>"GD"],
            ["name"=>"Greenland", "iso_code"=>"GL"],
            ["name"=>"Guatemala", "iso_code"=>"GT"],
            ["name"=>"Guam", "iso_code"=>"GU"],
            ["name"=>"Guyana", "iso_code"=>"GY"],
            ["name"=>"Hong Kong", "iso_code"=>"HK"],
            ["name"=>"Heard Island and McDonald Islands", "iso_code"=>"HM"],
            ["name"=>"Honduras", "iso_code"=>"HN"],
            ["name"=>"Croatia", "iso_code"=>"HR"],
            ["name"=>"Haiti", "iso_code"=>"HT"],
            ["name"=>"Hungary", "iso_code"=>"HU"],
            ["name"=>"Indonesia", "iso_code"=>"ID"],
            ["name"=>"Isle of Man", "iso_code"=>"IM"],
            ["name"=>"India", "iso_code"=>"IN"],
            ["name"=>"British Indian Ocean Territory", "iso_code"=>"IO"],
            ["name"=>"Ireland", "iso_code"=>"IE"],
            ["name"=>"Iran", "iso_code"=>"IR"],
            ["name"=>"Iraq", "iso_code"=>"IQ"],
            ["name"=>"Iceland", "iso_code"=>"IS"],
            ["name"=>"Israel", "iso_code"=>"IL"],
            ["name"=>"Italy", "iso_code"=>"IT"],
            ["name"=>"Jamaica", "iso_code"=>"JM"],
            ["name"=>"Jersey", "iso_code"=>"JE"],
            ["name"=>"Jordan", "iso_code"=>"JO"],
            ["name"=>"Japan", "iso_code"=>"JP"],
            ["name"=>"Kazakhstan", "iso_code"=>"KZ"],
            ["name"=>"Kenya", "iso_code"=>"KE"],
            ["name"=>"Kyrgyzstan", "iso_code"=>"KG"],
            ["name"=>"Cambodia", "iso_code"=>"KH"],
            ["name"=>"Kiribati", "iso_code"=>"KI"],
            ["name"=>"Saint Kitts and Nevis", "iso_code"=>"KN"],
            ["name"=>"South Korea", "iso_code"=>"KR"],
            ["name"=>"Kosovo", "iso_code"=>"XK"],
            ["name"=>"Kuwait", "iso_code"=>"KW"],
            ["name"=>"Laos", "iso_code"=>"LA"],
            ["name"=>"Lebanon", "iso_code"=>"LB"],
            ["name"=>"Liberia", "iso_code"=>"LR"],
            ["name"=>"Libya", "iso_code"=>"LY"],
            ["name"=>"Saint Lucia", "iso_code"=>"LC"],
            ["name"=>"Liechtenstein", "iso_code"=>"LI"],
            ["name"=>"Sri Lanka", "iso_code"=>"LK"],
            ["name"=>"Lesotho", "iso_code"=>"LS"],
            ["name"=>"Lithuania", "iso_code"=>"LT"],
            ["name"=>"Luxembourg", "iso_code"=>"LU"],
            ["name"=>"Latvia", "iso_code"=>"LV"],
            ["name"=>"Macau", "iso_code"=>"MO"],
            ["name"=>"Saint Martin", "iso_code"=>"MF"],
            ["name"=>"Morocco", "iso_code"=>"MA"],
            ["name"=>"Monaco", "iso_code"=>"MC"],
            ["name"=>"Moldova", "iso_code"=>"MD"],
            ["name"=>"Madagascar", "iso_code"=>"MG"],
            ["name"=>"Maldives", "iso_code"=>"MV"],
            ["name"=>"Mexico", "iso_code"=>"MX"],
            ["name"=>"Marshall Islands", "iso_code"=>"MH"],
            ["name"=>"North Macedonia", "iso_code"=>"MK"],
            ["name"=>"Mali", "iso_code"=>"ML"],
            ["name"=>"Malta", "iso_code"=>"MT"],
            ["name"=>"Myanmar", "iso_code"=>"MM"],
            ["name"=>"Montenegro", "iso_code"=>"ME"],
            ["name"=>"Mongolia", "iso_code"=>"MN"],
            ["name"=>"Northern Mariana Islands", "iso_code"=>"MP"],
            ["name"=>"Mozambique", "iso_code"=>"MZ"],
            ["name"=>"Mauritania", "iso_code"=>"MR"],
            ["name"=>"Montserrat", "iso_code"=>"MS"],
            ["name"=>"Mauritius", "iso_code"=>"MU"],
            ["name"=>"Malawi", "iso_code"=>"MW"],
            ["name"=>"Malaysia", "iso_code"=>"MY"],
            ["name"=>"Namibia", "iso_code"=>"NA"],
            ["name"=>"New Caledonia", "iso_code"=>"NC"],
            ["name"=>"Niger", "iso_code"=>"NE"],
            ["name"=>"Norfolk Island", "iso_code"=>"NF"],
            ["name"=>"Nigeria", "iso_code"=>"NG"],
            ["name"=>"Nicaragua", "iso_code"=>"NI"],
            ["name"=>"Niue", "iso_code"=>"NU"],
            ["name"=>"Netherlands", "iso_code"=>"NL"],
            ["name"=>"Norway", "iso_code"=>"NO"],
            ["name"=>"Nepal", "iso_code"=>"NP"],
            ["name"=>"Nauru", "iso_code"=>"NR"],
            ["name"=>"New Zealand", "iso_code"=>"NZ"],
            ["name"=>"Oman", "iso_code"=>"OM"],
            ["name"=>"Pakistan", "iso_code"=>"PK"],
            ["name"=>"Panama", "iso_code"=>"PA"],
            ["name"=>"Pitcairn Islands", "iso_code"=>"PN"],
            ["name"=>"Peru", "iso_code"=>"PE"],
            ["name"=>"Philippines", "iso_code"=>"PH"],
            ["name"=>"Palau", "iso_code"=>"PW"],
            ["name"=>"Papua New Guinea", "iso_code"=>"PG"],
            ["name"=>"Poland", "iso_code"=>"PL"],
            ["name"=>"Puerto Rico", "iso_code"=>"PR"],
            ["name"=>"North Korea", "iso_code"=>"KP"],
            ["name"=>"Portugal", "iso_code"=>"PT"],
            ["name"=>"Paraguay", "iso_code"=>"PY"],
            ["name"=>"Palestine", "iso_code"=>"PS"],
            ["name"=>"French Polynesia", "iso_code"=>"PF"],
            ["name"=>"Qatar", "iso_code"=>"QA"],
            ["name"=>"Romania", "iso_code"=>"RO"],
            ["name"=>"Russia", "iso_code"=>"RU"],
            ["name"=>"Rwanda", "iso_code"=>"RW"],
            ["name"=>"Saudi Arabia", "iso_code"=>"SA"],
            ["name"=>"Sudan", "iso_code"=>"SD"],
            ["name"=>"Senegal", "iso_code"=>"SN"],
            ["name"=>"Singapore", "iso_code"=>"SG"],
            ["name"=>"South Georgia", "iso_code"=>"GS"],
            ["name"=>"Solomon Islands", "iso_code"=>"SB"],
            ["name"=>"Sierra Leone", "iso_code"=>"SL"],
            ["name"=>"El Salvador", "iso_code"=>"SV"],
            ["name"=>"San Marino", "iso_code"=>"SM"],
            ["name"=>"Somalia", "iso_code"=>"SO"],
            ["name"=>"Saint Pierre and Miquelon", "iso_code"=>"PM"],
            ["name"=>"Serbia", "iso_code"=>"RS"],
            ["name"=>"South Sudan", "iso_code"=>"SS"],
            ["name"=>"São Tomé and Príncipe", "iso_code"=>"ST"],
            ["name"=>"Suriname", "iso_code"=>"SR"],
            ["name"=>"Slovakia", "iso_code"=>"SK"],
            ["name"=>"Slovenia", "iso_code"=>"SI"],
            ["name"=>"Sweden", "iso_code"=>"SE"],
            ["name"=>"Eswatini", "iso_code"=>"SZ"],
            ["name"=>"Sint Maarten", "iso_code"=>"SX"],
            ["name"=>"Seychelles", "iso_code"=>"SC"],
            ["name"=>"Syria", "iso_code"=>"SY"],
            ["name"=>"Turks and Caicos Islands", "iso_code"=>"TC"],
            ["name"=>"Chad", "iso_code"=>"TD"],
            ["name"=>"Togo", "iso_code"=>"TG"],
            ["name"=>"Thailand", "iso_code"=>"TH"],
            ["name"=>"Tajikistan", "iso_code"=>"TJ"],
            ["name"=>"Turkmenistan", "iso_code"=>"TM"],
            ["name"=>"Timor-Leste", "iso_code"=>"TL"],
            ["name"=>"Tonga", "iso_code"=>"TO"],
            ["name"=>"Trinidad and Tobago", "iso_code"=>"TT"],
            ["name"=>"Tunisia", "iso_code"=>"TN"],
            ["name"=>"Turkey", "iso_code"=>"TR"],
            ["name"=>"Tuvalu", "iso_code"=>"TV"],
            ["name"=>"Taiwan", "iso_code"=>"TW"],
            ["name"=>"Tanzania", "iso_code"=>"TZ"],
            ["name"=>"Uganda", "iso_code"=>"UG"],
            ["name"=>"United States Minor Outlying Islands", "iso_code"=>"UM"],
            ["name"=>"Uruguay", "iso_code"=>"UY"],
            ["name"=>"United States", "iso_code"=>"US"],
            ["name"=>"Ukraine", "iso_code"=>"UA"],
            ["name"=>"Uzbekistan", "iso_code"=>"UZ"],
            ["name"=>"Vatican City", "iso_code"=>"VA"],
            ["name"=>"Saint Vincent and the Grenadines", "iso_code"=>"VC"],
            ["name"=>"Venezuela", "iso_code"=>"VE"],
            ["name"=>"British Virgin Islands", "iso_code"=>"VG"],
            ["name"=>"United States Virgin Islands", "iso_code"=>"VI"],
            ["name"=>"Vietnam", "iso_code"=>"VN"],
            ["name"=>"Vanuatu", "iso_code"=>"VU"],
            ["name"=>"Wallis and Futuna", "iso_code"=>"WF"],
            ["name"=>"Samoa", "iso_code"=>"WS"],
            ["name"=>"Yemen", "iso_code"=>"YE"],
            ["name"=>"South Africa", "iso_code"=>"ZA"],
            ["name"=>"Zambia", "iso_code"=>"ZM"],
            ["name"=>"Zimbabwe", "iso_code"=>"ZW"]
        ];

        DB::table('countries')->insert($countries);

        $all_saved_countries = Country::all();
        foreach ($all_saved_countries as $saved_country) {
            $uploadedFlag = new UploadedFile(storage_path("fixtures/pictures/flags/" . strtolower($saved_country->iso_code) . ".png"), strtolower($saved_country->iso_code) . '.png');
            if ($uploadedFlag) {
                $saved_country->saveImage($uploadedFlag);
            }
        }
    }
}
